<div class="website-logo">
    <a href="#">
        <div class="logo">
            <img class="logo-size" src="/inscription/themes/dist/assets/img/flat-logo.png" alt="">
        </div>
    </a>
</div>
<div class="row">
    <div class="img-holder">
        <div class="bg"></div>
        <div class="info-holder">
            <img class="md-size" src="/inscription/themes/dist/assets/css/graphic7.png" alt="">
        </div>
    </div>
    <div class="form-holder">
        <div class="form-content">
            <div class="form-items">
                <h3 class="form-title" style="color: #934ba0">Inscription sur passvola</h3>
                <ul class="nav" id="stepsTabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link" id="linear-progress">Etape 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="linear-progress">Etape 2</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="">Etape 3</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="">Etape 4</a>
                    </li>
                </ul>
                <form method="POST" action="/roles/role/createParrain">
                    <input type="hidden" name="id_appli" id="id_appli" value="<?= $user->id ?>">
                    <input type="hidden" name="username_appli" id="username_appli" value="<?= $user->username ?>">
                    <input type="hidden" name="nom_pack" id="nom_pack">
                    <input type="hidden" name="parent_id" id="parent_id">
                    <div class="separator"></div>
                    <div class="tab-content" id="stepsTabContent">
                        <div class="tab-pane fade active show" id="step1" role="tabpanel" aria-labelledby="step1-tab">
                            <div class="tab-pane active" id="step2" role="tabpanel" aria-labelledby="step2-tab">
                                <div class="form-subtitle">2. Choix du parrain</div>
                                <input type="text" class="form-control" placeholder="Nom du parrain"
                                       name="parent_username"
                                       id="parent_username">
                            </div>
                            <div class="separator"></div>
                            <div class="form-button">
                                <button id="submit" type="submit" class="ibtn">Suivant</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="/themes/js/typeahead.js"></script>
<script type="application/javascript">

    $(function () {
        $(document).on('change', '#parent_username', function () {
            var username = $(this).val();
            $.ajax({
                url: '/systemes/profil/getParent/username/' + username,
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        $('#nom_pack').val(data.pack);
                        $('#parent_id').val(data.id_appli)
                    }
                }
            });
        });
    });
</script>