<div class="row">
    <div class="col-lg-12">
        <h4 class="card-footer page-header text-center">Modifier votre profil</h4>
        <br>
    </div>
</div>
<form method="post" action="/roles/role/modifier">
    <div class="col-md-12 row">
        <div class="col-md-4"></div>
        <div class="col-md-4 center-block">
            <div class="card card-purple card-outline">
                <div class="card-body box-profile">
                    <div class="text-center">
                        <a href=""><img class="profile-user-img img-fluid img-circle"
                             src="/themes/dist/img/avatar6.png"
                                alt="User profile picture"></a>
                    </div>
                    <input type="hidden" value="<?= $data['id']?>" name="id">
                    <input type="hidden" value="<?= $data['id_appli']?>" name="id_appli">
                    <input type="hidden" value="<?= $data['username_appli'] ?>" name="username_appli">
                    <h3 class="profile-username text-center"><?= $data['username_appli'] ?></h3>
                    <p class="text-muted text-center">Utilisateur</p>
                    <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Nom</b> <a class="float-right">
                                <input type="text" class="form-control" name="nom" value="<?= $data['nom'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Prénom</b> <a class="float-right">
                                <input type="text" class="form-control" name="prenom" value="<?= $data['prenom'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Téléphone</b><a class="float-right">
                                <input type="text" class="form-control" name="telephone" value="<?= $data['telephone'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Email</b> <a class="float-right">
                                <input type="text" class="form-control" name="mail" value="<?= $data['mail'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Adresse</b> <a class="float-right">
                                <input type="text" class="form-control" name="adresse" value="<?= $data['adresse'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>N°CIN</b> <a class="float-right">
                                <input type="text" class="form-control" name="identite" value="<?= $data['identite'] ?>">
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Pack</b> <a class="float-right">
                                <input type="text" class="form-control" name="pack" value="<?= $data['pack'] ?>" readonly>
                            </a>
                        </li>
                        <li class="list-group-item">
                            <b>Parrain</b> <a class="float-right">
                                <input type="text" class="form-control" name="parent_username"
                                       value="<?= $data['parent_username'] ?>" readonly>
                            </a>
                        </li>
                    </ul>
                    <button class="btn btn-info btn-block" type="submit"><b>Enregistrer</b></button>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</form>

