<style type="text/css">
    body{            
        font-family: MavenPro, Helvetica, sans-serif;
        font-size: 9px!important;

    }
    table {
        border-collapse: collapse;
    }

    table, table th, table td {
        border: 1px solid black;
        padding: 1px!important;
    }  

    .table-sign, .table-sign td, .table-sign th{        
        border: none;
        padding-left: 75px;
    }
    thead { display: table-header-group }
    tfoot { display: table-row-group }
    table { page-break-inside:auto }
    tr { page-break-inside:avoid; page-break-after:auto }


    .footer{
        font-weight: bold
    }
    div.page{
        page-break-before: always;
    }
    table u{
        font-weight: bold;
    }
</style>