<?php
$crumbs = Layout::getCrumbs();
if (isset($crumbs[0]) && count($crumbs) > 0): $crumbs = $crumbs[0];
?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                <ol class="breadcrumb float-sm-right">
                    <?php foreach ($crumbs as $crumb): ?>
                        <?php if (!$crumb['isActive']): ?>
                            <li class="breadcrumb-item">
                                <a href="<?=$crumb['url']?>">
                                    <?=$crumb['label']?>
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="breadcrumb-item active"><?= $crumb['label'] ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
