<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3 class="modal-title"><?= $title ?></h3>
            </div>
            <div class="modal-body">
                <h5><?= $content ?></h5>
            </div>
            <div class="modal-footer">
                <a class="btn confirmation-validation" target="_blank">Oui</a>
                <a class="btn confirmation-cancel" data-dismiss="modal">Annuler</a>
            </div>
        </div>
    </div>
</div>
