<?php
$oSession = new Session();
$userInfos = $oSession->getUser();
$userRoleId = 0;
if (isset($userInfos->role_id)) {
    $userRoleId = (int) $userInfos->role_id;
}
$menus = Apps::getMenu($userRoleId);
?>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <?php foreach ($menus as $module) : ?>
                <?php $isCurModule = Request::isCurrentModule($module['slug'], ' ') ?>
                <li class="<?php echo $isCurModule ? 'active' : '' ?>">
                    <a href="<?php echo ($module['link']) ? Request::getUrl($module['link']) : '#' ?>">
                        <i class="material-icons"><?php echo $module['icon'] ?></i>
                        <span class="label-menu"><?php echo $module['label'] ?></span>
                    </a>
                    <?php if (isset($module['child'])) : ?>
                        <ul class="nav nav-second-level <?php echo $isCurModule ? 'collapse in' : '' ?>">
                            <?php foreach ($module['child'] as $controller): ?>
                                <?php $isCurController = Request::isCurrentController($controller['link']) ?>
                                <li class="menu-item <?php echo $isCurController ? 'active' : '' ?>">
                                    <a href="<?php echo Request::getUrl($controller['link']) ?>">
                                        <i class="material-icons"><?php echo $controller['icon'] ?></i>
                                        <span class="label-menu"><?php echo $controller['label'] ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script>
    $(function () {
        $('.menu-item.active').parent().addClass('collapse in').parent().addClass('active');
    });
</script>