<!-- Left navbar links -->
<!--<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
    </li>
</ul>-->

<!-- SEARCH FORM -->
<!-- <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </div>
</form> -->

<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
        <?php
        $oSession = new Session();
        $dataSession = $oSession->getUser();
        /**@var Roles_RolesModel $oRoles*/
        $oRoles = Apps::getModel('Roles_Roles');
        $dataUserPassvola = $oRoles->getBy(['username_appli' => $dataSession->username]);
        ?>
        <a class="nav-link" data-toggle="dropdown" href="#">
            <div class="user-panel ">
                <img src="/themes/dist/img/avatar6.png" class="img-circle elevation-2" alt="User Image">
                <?=  isset($dataSession->lastname)? $dataSession->username. ' ' : '' ?>
                (<?=  isset($dataSession->lastname)? $dataSession->role_name. ' ' : '' ?>)
            </div>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <?php if ($dataSession->role_id == 2): ?>
                <div class="image text-center" style="margin-top: 20px; margin-bottom: 20px;">
                    <a href="/systemes/profil/liste">
                        <img src="/themes/dist/img/avatar6.png" style="width: 45%;" class="img-circle elevation-2" alt="User Image">
                    </a>
                </div>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i>
                    <b>Username: </b>
                    <span class="float-right text-muted text-sm">
                        <?=  isset($dataSession->lastname)? $dataSession->username. ' ' : '' ?>
                    </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item"><b>Nom:</b>
                    <span class="float-right text-muted text-sm">
                        <?=  isset($dataSession->lastname)? $dataSession->lastname. ' ' : '' ?>
                    </span>
                </a>
                <a href="#" class="dropdown-item">
                    <b>Prénom:</b>
                    <span class="float-right text-muted text-sm">
                        <?=  isset($dataSession->lastname)? $dataSession->firstname. ' ' : '' ?>
                    </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <b>Rôle: </b>
                    <span class="float-right text-muted text-sm"><?= $dataSession->role_name ?></span>
                </a>
            <?php else: ?>
                <div class="image text-center" style="margin-top: 20px; margin-bottom: 20px;">
                    <a href="/systemes/profil/liste">
                        <img src="/themes/dist/img/avatar6.png" style="width: 45%;" class="img-circle elevation-2" alt="User Image">
                    </a>
                </div>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i>
                    <b>Username: </b>
                    <span class="float-right text-muted text-sm">
                    <?=  isset($dataSession->lastname)? $dataSession->username. ' ' : '' ?>
                </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item"><b>Nom:</b>
                    <span class="float-right text-muted text-sm">
                    <?= (is_null($dataUserPassvola)) ? '' :$dataUserPassvola[0]['nom'] ?>
                </span>
                </a>
                <a href="#" class="dropdown-item">
                    <b>Prénom:</b>
                    <span class="float-right text-muted text-sm">
                    <?= (is_null($dataUserPassvola)) ? '' : $dataUserPassvola[0]['prenom'] ?>
                </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <b>Rôle: </b>
                    <span class="float-right text-muted text-sm"><?= $dataSession->role_name ?></span>
                </a>
            <?php endif;?>
            <div class="dropdown-divider"></div>
            <a href="/index/logout" class="dropdown-item dropdown-footer"><b>Deconnexion</b></a>
        </div>
    </li>
</ul>
