<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>passvola | Administration</title>
    <link rel="icon" type="image/png" href="/themes/dist/img/logo.png">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/themes/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/themes/dist/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="/themes/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/themes/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/themes/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/themes/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="/themes/dist/css/adminlte.css">
    <link rel="stylesheet" href="/themes/css/evolution.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/themes/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/themes/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="/themes/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <!- script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script  -->
    <!--script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script -->
    <!--[endif]-->

    <!-- jQuery -->
    <script src="/themes/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/themes/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/themes/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="/themes/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="/themes/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="/themes/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="/themes/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/themes/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="/themes/plugins/moment/moment.min.js"></script>
    <script src="/themes/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/themes/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="/themes/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/themes/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/themes/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/themes/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/themes/dist/js/demo.js"></script>
</head>

<?php
$oSession = new Session();
$dataSession = $oSession->getUser();
/**@var Roles_RolesModel $oRoles*/
$oRoles = Apps::getModel('Roles_Roles');
$dataUserPassvola = $oRoles->getBy(['username_appli' => $dataSession->username]);
$notif = $oRoles->countNotValid();
?>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-dark navbar-purple">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                <!--<li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>-->
            </ul>
            <?php if ($dataSession->role_id == 2): ?>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-danger navbar-badge"><?= $notif['not_valid'] ?></span>
                    </a>
                </li>
            </ul>
            <?php endif; ?>
            <?php Layout::render('part/navbar'); ?>
        </nav>

        <aside class="main-sidebar sidebar-light-purple elevation-4">
            <?php Layout::render('part/menu-aside'); ?>
        </aside>

        <div class="content-wrapper">

            <?php Layout::render('part/breadcrumb'); ?>

            <div class="content-header">
                <?php echo Layout::renderView($content) ?>
            </div>
        </div>
    </div>
    <?php Layout::render('part/footer'); ?>
</body>

</html>