<!DOCTYPE html>
<html lang="fr">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>passvola | Connexion</title>
    <link rel="icon" type="image/png" href="/themes/dist/assets/img/logo.png">
    <link rel="stylesheet" type="text/css" href="/themes/dist/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/themes/dist/assets/css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="/themes/dist/assets/css/iofrm-style.css">
    <link rel="stylesheet" type="text/css" href="/themes/dist/assets/css/iofrm-theme8.css">

    <link rel="stylesheet" href="/themes/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="/themes/dist/css/adminlte.css">

</head>
<body>

<script src="/themes/dist/assets/js/jquery.min.js"></script>
<script src="/themes/dist/assets/js/popper.min.js"></script>
<script src="/themes/dist/assets/js/bootstrap.min.js"></script>
<script src="/themes/dist/assets/js/main.js"></script>

<div class="form-body">
    <?php echo Layout::renderView($content) ?>
</div>

</body>
</html>