<?php
$user = $datas['user'];
$roles = $datas['roles'];
?>
<div class="header-page">
    <div class="row">
        <div class="col-lg-12">
            <h4 class="card-footer page-header text-center">Modifier un utilisateur</h4>
            <br>
        </div>
    </div>
</div>

<form method="POST" class="form-horizontal" action="/systemes/user/save" id="user-creation">
    <input type="hidden" name="id" value="<?=  $user->id ?>" >
    <div class="form-container">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label" for="lastname">Nom </label>
                    <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Nom de l'utilisateur" value="<?php
                    if (isset($user->lastname)) {
                        echo $user->lastname;
                    }
                    ?>"  required="">
                </div>
                <div class="form-group">
                    <label class="control-label " for="username">Nom d'utilisateur </label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Pseudo" readonly  value="<?php
                    if (isset($user->username)) {
                        echo $user->username;
                    }
                    ?>"  required="">
                </div>
                <input type="hidden" id="last_role" name="last_role" value="<?= $user->role_id ?>">
                <div class="form-group">
                    <label class="control-label " for="role_code">Rôle </label>
                    <select id="role_code" name="role_code" class="form-control"  required="">
                        <?php if (isset($roles) && count($roles) > 0): ?>
                            <?php foreach ($roles as $role): ?>
                                <option <?php
                                if (isset($user->role_id) && $user->role_id != "" && $user->role_id == $role->id) {
                                    echo 'selected="selected"';
                                }
                                ?> value="<?php echo $role->code ?>" data-id="<?= $role->id ?>"> <?php echo $role->role_name ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                    </select>
                </div>
                 <div class="form-group hidden role_updated">
                    <label class="control-label " for="resolution">Résolution </label>
                    <input type="text" class="form-control" id="Résolution" name="resolution" placeholder="Résolution">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label " for="firstname">Prénom </label>
                    <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Prénom de l'utilisateur" value="<?php
                    if (isset($user->firstname)) {
                        echo $user->firstname;
                    }
                    ?>"  required="">
                </div>
                <div class="form-group">
                    <label class="control-label" for="password">Mot de passe </label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Mot de pass"  value="<?php
                    if (isset($user->password)) {
                        echo $user->password;
                    }
                    ?>"  required="">
                </div>

                 <div class="form-group hidden role_updated">
                    <label class="control-label " for="motif">Motif  du remplacement</label>
                    <input type="text" class="form-control" id="motif" name="motif" placeholder="Motif du remplacement">
                </div>
            </div>
        </div>
    </div>
    <div class="action-group">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class=" col-md-6">
                        <button type="submit" class="btn btn-default alert-success center">Sauvegarder</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
$(function(){
    $('#role_code').change(function(){
        if($(this).children("option:selected").data('id') != $('#last_role').val()){
            $('.role_updated').removeClass('hidden');
            $('.role_updated input').attr('required', 'required');
        }else{
            $('.role_updated').addClass('hidden');
            $('.role_updated input').removeAttr('required');
        }
    });
})
</script>