<div class="header-page">
    <div class="row title-container">
        <div class="col-md-12 title-block">
            <h3 class="page-title">Modifier un rôle</h3>
        </div>
    </div>
</div>

<form method="POST" class="form-horizontal form-valida" action="<?php echo  '/' . 'systemes/role/save' ?>" id="user-creation">
    <input type="hidden" name="id" value="<?= $role->id ?>">
    <div class="form-container one-column">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="control-label" for="code">Code </label>
                    <input readonly type="text" class="form-control" name="code" id="code" placeholder="Code" value="<?php if (isset($role->code)) echo $role->code; ?>"  required="">
                </div>
                <div class="form-group">
                    <label class="control-label" for="role_name">Nom du role </label>
                    <input type="text" class="form-control" id="role_name" name="role_name" placeholder="Nom du role" value="<?php if (isset($role->role_name)) echo $role->role_name; ?>"  required="">
                </div>
            </div>
        </div>
    </div>

    <div class="action-group">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class=" col-md-6">
                        <button type="submit" class="btn btn-default alert-success center">Sauvegarder</button>
                    </div>
                    <div class=" col-md-6 right">
                        <button type="button" class="btn btn-default btn-cancel center annuler" onclick="history.back()">Annuler</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    /**
     * Validation des formulaires
     */
    $("form#role-edition").validate();
</script>
