<?php
$tabUrl = parse_url($_SERVER ['REQUEST_URI']);
$part_uri = '?' . View::getDataIn($tabUrl, 'query');
?>
<div class="header-page">
    <div class="row title-container">
        <div class="col-md-10 title-block">
            <h4 class="text-center page-title">Liste des liens et permissions</h4>
        </div>
        <div class="col-md-2 link-element">
            <div class="add-link link-with-icon">
                <a href="/systemes/link/create">
                    <i class="fa fa-plus-circle"></i>
                    <span>Ajout lien</span>
                </a>
            </div>
        </div>
    </div>
</div>
<form action="/systemes/link/liste/" method="GET">
    <!--<div class="header-filter">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="titre" class="control-label">Titre</label>
                    <input type="text" class="form-control" name="titre" id="titre" value="<?/*= View::getDataIn($aData, 'titre') */?>">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name" class="control-label">Lien</label>
                    <input type="text" class="form-control" name="urls_segment" id="name" value="<?/*= View::getDataIn($aData, 'urls_segment') */?>">
                </div>
            </div>
            <div class="col-md-2">
                <button class="bottom-right alert-success btn btn-filter" type="submit" >Filtrer</button>
            </div>
        </div>
    </div>-->

    <div class="card-footer header-filter">
        <div class="text-left">
            <label for="titre" class="control-label">Titre: </label>
                <input type="text" class="col-md-4" name="titre" value="<?= View::getDataIn($aData, 'titre') ?>">
            <label for="urls_segment" class="control-label">Lien: </label>
                <input type="text" class="col-md-4" name="urls_segment" value="<?= View::getDataIn($aData, 'urls_segment') ?>">
            <button class="bottom-right alert-success btn btn-filter" type="submit" >Filtrer</button>
        </div>
    </div>

</form>

<table class="table table-hover table-striped dataTable">
    <thead>
        <tr>
            <th><a href="<?= View::urlToSort('titre') ?>">Titre<i class="fa fa-caret-down"></i></a></th>
            <th><a href="<?= View::urlToSort('urls_segment') ?>">Lien<i class="fa fa-caret-down"></i></a></th>
            <th colspan="3" class=" action-cell centered">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($aLinks as $aLink): ?>
            <tr>
                <td><?= $aLink['titre'] ?></td>
                <td><?= $aLink['urls_segment'] ?></td>
                <td class="action-cell">
                    <a class="permission" href="<?= '/systemes/link/loadpermission/id/' . $aLink['id'] . '/redirect/' . $part_uri ?>" data-toggle="tooltip" title="Permission" data-placement="bottom">
                        <i class="fa fa-lock"></i>
                    </a>
                </td>
                <td class="action-cell">
                    <?php if ($aLink['notDeletable'] != 1) : ?>
                        <a href="<?= '/systemes/link/edit/id/' . $aLink['id'] . '/redirect/' . $part_uri ?>" data-toggle="tooltip" title="Modifier" data-placement="bottom">
                            <i class="fa fa-edit"></i>
                        </a>
                    <?php endif; ?>
                </td>
                <td class="action-cell">
                    <?php if ($aLink['notDeletable'] != 1) : ?>
                        <a href="<?= '/systemes/link/delete/id/' . $aLink['id'] . '/redirect/' . $part_uri ?>" data-toggle="tooltip" title="Effacer" data-placement="bottom">
                            <i class="fa fa-trash"></i>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="modal fade" id="modal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Configuration permission</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<?php
Layout::render('part/pagination', compact('pagination'));
?>

<script type="text/javascript">
    $(function () {
        $('.permission').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                success: function (html) {
                    $('#modal .modal-body').html(html);
                    $('#modal').modal('show');
                }
            });
        });
    });
</script>