<div id="myDiagramDiv" style="width:100%; height:640px; background-color: #ffffff;">
</div>

<script src="/themes/js/go-debug.js"></script>
<script>
   /* $(function () {
        $('#tree').on('click', function () {*/

            var value = <?= json_encode($data) ?>;
            console.log(value);
            var $ = go.GraphObject.make;
            var myDiagram =
                $(go.Diagram, "myDiagramDiv",
                    {
                        "undoManager.isEnabled": true, // enable Ctrl-Z to undo and Ctrl-Y to redo
                        layout: $(go.TreeLayout, // specify a Diagram.layout that arranges trees
                            { angle: 90, layerSpacing: 35 })
                    });

            // the template we defined earlier
            myDiagram.nodeTemplate =
                $(go.Node, "Horizontal",
                    { background: "#6f42c1"},
                    $(go.Picture,
                        { margin: 10, width: 50, height: 50, background: "white"},
                        new go.Binding("source")),
                    $(go.TextBlock, "Default Text",
                        { margin: 12, stroke: "white", font: "bold 16px sans-serif"},
                        new go.Binding("text", "name"))
                );

            var model = $(go.TreeModel);
            model.nodeDataArray = value;
                /*[
                    { key: "1", parent: "", name: "Admin",   source: "/themes/dist/img/avatar6.png" },
                    { key: "2", parent: "1", name: "Demeter",    source: "cat2.png" },
                    { key: "3", parent: "1", name: "Copricat",   source: "cat3.png" },
                ];*/
            myDiagram.model = model;

   /*     });
    });*/
</script>