<div class="row">
    <div class="col-lg-12">
        <h4 class="card-footer page-header text-center">Détails</h4>
        <br>
    </div>
</div>
<div class="row col-md-12">
    <div class="col-md-10"></div>
    <div class="col-md-2 link-element">
        <div class="add-link link-with-icon">
            <a href="/systemes/profil/transaction/id/<?= $data['id_appli'] ?>/username/<?= $data['username_appli']?>">
                <i class="fa fa-plus-circle"></i>
                <span>Ajout transaction</span>
            </a>
        </div>
    </div>
</div>
<br>
<div class="col-md-12">
    <div class="card">
        <div class="card-header pr-2">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#debit" data-toggle="tab">Détail</a></li>
                <li class="nav-item"><a class="nav-link" href="#credit" data-toggle="tab">Détail solde</a></li>
                <li class="nav-item"><a class="nav-link" href="#solde" data-toggle="tab">Solde</a></li>
            </ul>
        </div>
        <div class="card-body">
            <div class="tab-content">
                <div class="active tab-pane" id="debit">
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>

                                </thead>
                                <tbody>
                                <tr>
                                    <td style="width: 25%;"><b>Nom d'utilisateur</b></td>
                                    <td><?= $data['username_appli'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Parrain</b></td>
                                    <td><?= $data['parent_username'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Pack</b></td>
                                    <td><?= $data['pack'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Nom</b></td>
                                    <td><?= $data['nom'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Prénom</b></td>
                                    <td><?= $data['prenom'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Mail</b></td>
                                    <td><?= $data['mail'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Téléphone</b></td>
                                    <td><?= $data['telephone'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Adresse</b></td>
                                    <td><?= $data['adresse'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>CIN</b></td>
                                    <td><?= $data['identite'] ?></td>
                                </tr>
                                <tr>
                                    <td><b>Date d'inscription</b></td>
                                    <td><?= Apps::convertDate($data['date_confirmation'], 'd/m/Y') ?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
                <div class="tab-pane" id="credit">
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Bonus direct</th>
                                    <th>Bonus indirect</th>
                                    <th>Montant</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><?= $bonus['gainDirect'] ?></td>
                                    <td><?= $bonus['gainIndirect'] ?></td>
                                    <td><?= $bonus['finalValue'] ?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th style="width: 30%;">Date du mouvement</th>
                                    <th>Description</th>
                                    <th>Type</th>
                                    <th>Montant</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($mouvement as $item): ?>
                                <tr>
                                    <td><?= Apps::convertDate($item['date_mouvement'], 'd/m/Y') ?></td>
                                    <td><?= $item['mouvement'] ?></td>
                                    <td><?= $item['mode'] ?></td>
                                    <td><?= $item['valeur'] ?></td>
                                </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
                <div class="tab-pane" id="solde">
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Total Débit</th>
                                    <th>Total Crédit</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $debitSolde = $debit['debit'] + $bonus['finalValue'];
                                $creditSolde = $credit['credit'];
                                $totalSolde = $debitSolde - $creditSolde;
                                ?>
                                <tr>
                                    <td></td>
                                    <td><?=  $debitSolde ?></td>
                                    <td><?= $creditSolde ?></td>
                                </tr>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td><b>SOLDE</b></td>
                                    <td style="text-align: center; font-size: 25px; font-weight: bold; background: #acbad5" colspan="2">
                                        <?= Apps::convertMoney($totalSolde) ?> Ar
                                    </td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
