<div class="col-md-2 link-element text-center">
    <div class="add-link link-with-icon">
        <a href="/systemes/user/create">
            <i class="fa fa-plus-circle"></i>
            <span>Ajout utilisateur</span>
        </a>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <h4 class="card-footer page-header text-center">Profil</h4>
        <br>
    </div>
    <br>
</div>

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Liste des membres</h5>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                <i class="fas fa-times"></i></button>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
            <tr>
                <th style="width: 15%">Nom d'utilisateur</th>
                <th>Parent</th>
                <th style="width: 5%">Image</th>
                <th style="width: 10%">Nom</th>
                <th>Télephone</th>
                <th style="width: 15%">Adresse</th>
                <th>Pack</th>
                <th style="width: 5%" class="text-center">Status</th>
                <th style="width: 20%">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $item): ?>
                <tr>
                    <td><a><?= $item['username_appli'] ?></a>
                        <br/><small>Créer le: <?= Apps::convertDate($item['date_confirmation'], 'd.m.Y') ?></small>
                    </td>
                    <td><?= $item['parent_username'] ?></td>
                    <td>
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <img alt="Avatar" class="table-avatar" src="/themes/dist/img/avatar6.png">
                            </li>
                        </ul>
                    </td>
                    <td><?= $item['nom'] ?> <?= $item['prenom'] ?></td>
                    <td class="project_progress"><?= $item['telephone'] ?></td>
                    <td><?= $item['adresse'] ?></td>
                    <td><?= $item['pack'] ?></td>
                    <?php if ($item['confirme_check'] != 'validee'): ?>
                        <td class="project-state"><span class="badge badge-danger">Non Validée</span></td>
                    <?php else: ?>
                        <td class="project-state"><span class="badge badge-success">Validée</span></td>
                    <?php endif; ?>
                    <td class="project-actions text-right">
                        <?php if (($item['confirme_check'] == 'validee') || ($item['username_appli'] == 'admin')): ?>
                            <a class="btn btn-success btn-sm" href="#">
                                <i class="fas fa-check"></i>
                            </a>
                        <?php else: ?>
                            <a class="btn btn-info btn-sm" href="/systemes/profil/confirmer/id/<?= $item['id'] ?>">
                                <i class="fas fa-check"></i>Confirmer
                            </a>
                        <?php endif; ?>
                        <a class="btn btn-primary btn-sm" href="/systemes/profil/detail/id/<?= $item['id'] ?>">
                            <i class="fas fa-folder"></i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="#">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php
Layout::render('part/pagination', compact('pagination'));
?>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <?php if ($passvola_info): ?>
                <div></div>
            <?php else: ?>

            <?php endif; ?>
        </div>
    </div>
</section>

